# Generated by Django 3.1.5 on 2021-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='directorinfo',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
    ]
