# Generated by Django 3.1.5 on 2021-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='directorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('peopleCode', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='movieInfo',
        ),
    ]
