# Generated by Django 3.1.5 on 2021-02-11 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0002_auto_20210122_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directorinfo',
            name='photo',
            field=models.ImageField(default='media/no_img.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
