# Generated by Django 3.1.5 on 2021-02-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0003_auto_20210211_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorinfo',
            old_name='photo',
            new_name='image',
        ),
    ]
