# Generated by Django 3.1.5 on 2021-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0004_auto_20210211_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorinfo',
            name='wisesaying',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='directorinfo',
            name='image',
            field=models.ImageField(blank=True, default='media/no_img.png', null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
