# Generated by Django 3.1.5 on 2021-03-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0006_writerinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WriterInfo',
            new_name='FicWriterInfo',
        ),
    ]
