# Generated by Django 3.1.5 on 2021-03-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0008_ficwriterinfo_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficwriterinfo',
            name='job',
        ),
    ]
