# Generated by Django 3.1.5 on 2021-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieDrtr', '0010_ficwriterinfo_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFicWriterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('peopleCode', models.IntegerField()),
                ('job', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
